print("==========BIODATA===========")
print( )
print("-------DATA PRIBADI-------")
nama=input("masukkan nama          :")
alamat=input("masukkan alamat        :")
umur=input("masukkan umur          :")
jk=input("masukkan jenis kelamin :")
hobi=input("masukkan hobi          :")
print( )
print("-------PENDIDIKAN---------" )
sd=input("masukkan sd   :")
mts=input("masukkan mts  :")
smk=input("masukkan smk  :")
print( )
print("-----PERGURUAN TINGGI-----")
kampus=input("masukkan kampus        :")
prodi=input("masukkan prodi/jurusan :")
semester=input("masukkan semester      :")
nim=input("masukkan nim           :")
print( )
print( "======DATA PRIBADI======")
print("Nama Anda          : ",nama)
print("Alamat Anda        : ",alamat)
print("Umur Anda          : ",umur)
print("Jenis Kelamin Anda : ",jk)
print("Hobi Anda          : ",hobi)
print( )
print( "=======PENDIDIKAN=======")
print("Sd Anda               : ",sd)
print("Mts Anda              : ",mts)
print("SMK Anda              : ",smk)
print( )
print( "====PERGURUAN TINGGI====")
print("Kampus Anda        : ",kampus)
print("Prodi/Jurusan Anda : ",prodi)
print("Semester Anda      : ",semester)
print("Nim Anda           : ",nim)

